### PR TITLE
form added

### PR DESCRIPTION
**Pull request by saivivek116**
Addded Contact form in faq page

### CODE REVIEW

**Review by gokulprathin8 — APPROVED** [review]
LGTM

**Comment by gokulprathin8** [comment]
the markdown changes are missing. Are you going to make them in a different PR? @saivivek116 ?

**Comment by saivivek116** [comment]
For now i have added 2 more faqs. Lets add more faqs eventually.

**Comment by gokulprathin8** [comment]
ok you can merge, those changes are just text related. should be fine.

**Review by ZihengSun — APPROVED** [review]
lg

**Pull request merged**
