### PR TITLE
add updating geoweaver section in installation.md

### PR DESCRIPTION
**Pull request by srinijammula**
Updated installation guide on [Geoweaver Site](https://geoweaver.dev/blog/installation/) for users to update Geoweaver when a new version is released. Added steps for JAVA, Application, developers, and pygeoweaver users.

image

### CODE REVIEW

**Comment by varun-TR** [comment]
looks good

**Comment by ZihengSun** [comment]
@varun-TR can you approve it if it looks ok for you?

**Comment by varun-TR** [comment]
> @varun-TR can you approve it if it looks ok for you?

Professor, i need access for approving. Can you please give me?

**Comment by ZihengSun** [comment]
@varun-TR sure, check your inbox

**Pull request merged**
